import type { Metadata } from "next";
import { Pacifico } from "next/font/google";
import {SignInButton, SignedIn, SignedOut, UserButton} from '@clerk/nextjs'
import "./globals.css";
import Provider from "@/components/provider";
import Navbar from "@/components/Navbar";
import "@uploadthing/react/styles.css";


const pacifico = Pacifico({subsets: ['vietnamese'], weight:'400'})

export const metadata: Metadata = {
  title: "chat-with-pdf",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pacifico.className + " bg-gradient-to-r from-rose-100 via-indigo-200 to-teal-100"}>
        <Provider>
          <Navbar/>
          {children}
        </Provider>
      </body>
    </html>
  );
}
